import type { Metadata } from "next";
import "./../styles/index.scss";
import { Navbar } from "@/components/organism/Navbar/Nabar";
import NavbarSlider from "@/components/organism/NavbarSlider/NavbarSlider";
import StoreProvider from "@/store/StoreProvider";

export const metadata: Metadata = {
  title: "Ruffy Poster",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider> 
          <NavbarSlider />
          <Navbar />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
