import type { Metadata } from "next";
import "./../styles/index.scss";
import { Navbar } from "@/components/organism/Navbar/Nabar";

export const metadata: Metadata = {
  title: "Ruffy Poster",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
